### ISSUE TITLE
可以问问题吗？ 我想知道登录后系统怎么就跳到home页面了

### ISSUE THREAD

**Issue by uniquejava** [gudepeng/vue-giant#4]
登录：

```js
 handleLogin() {
      this.$store.dispatch('user/login', this.loginForm).then(() => {
        this.showLogin = false
      })
    },
```
store里面 user/login

```js
  login({ commit }, userInfo) {
    // TODO 登录获取用户token
    const userToken = userInfo.username
    // END 登录获取用户token
    setUserToken(userToken)
    commit('SET_TOKEN', userToken)
  },
```
这个并没有 `router.push('/home')`， 怎么url就跳转了。 请指教。 方便加wx？ id： `uniquejava`

**Comment by gudepeng** [comment]
await this.$store.dispatch('user/login', this.loginForm).then(() => {
            this.$router.push({ path: '/home' })
            // window.history.pushState({}, '', '/home')
            this.loading = false
          })

登录页面（login/index.vue）72行
